### ISSUE TITLE
Game Script?

### ISSUE THREAD

**Issue by mosquitobird11** [HoratioVex/Chocobo-Land-Translation#1]
Hey @HoratioVex ! Do you happen to have a way to dump or upload an existing Japanese game script (even if incomplete) for this game? It would be very useful in forcing OCR programs like Game2Text to work with it and enable Japanese learners like myself to play along in JP and do dictionary lookups and hook into Anki easily.

**Comment by mosquitobird11** [comment]
Don't worry about this too much, I finally got OCR to work after changing it to an online service and binarizing.

**Comment by HoratioVex** [comment]
I didn't see the issue earlier since you closed it immediately, but the repository contains everything you need to dump the script from the ROM. You need "choco_commands.txt", "choco table.txt" and the text dumper Cartographer (https://www.romhacking.net/utilities/647/), all in one folder. Then run 'cartographer "romname.gba" "choco_commands.txt" scriptdump -s'
